### ISSUE TITLE
Test the pacakge by installing it through npm.

### ISSUE THREAD

**Issue by electr0de** [DefineX-Studios/parsec-account-switcher#11]
(Wait till package is published, npm has placed a 24 hours ban due to unpublish, will be published 22nd July IST 5:30 PM)
Installation : npm install -g parsec-switcher

Done by:
- [x] @adsau59 
- [ ] @Enigmazflo 
- [ ] @nayaablakhani 

Test Actions:

- Setup
- Add acccount
- switch account
- delete account
- list accounts

**Comment by adsau59** [comment]
done, reassigning issue back to you

**Comment by electr0de** [comment]
@Enigmazflo Test from source

**Comment by electr0de** [comment]
No longer published to npm
