### ISSUE TITLE
"ERROR: The process "pservice.exe" not found." with elevated rights

### ISSUE THREAD

**Issue by adsau59** [DefineX-Studios/parsec-account-switcher#12]
when an account is added while parsec is running with an elevated terminal you get this error

STR:
1. run terminal as admin
2. open parsec
3. run this command `parsec-switcher -a banana`

notice you will get this error "ERROR: The process "pservice.exe" not found."

Screenshot:
![WindowsTerminal_FKrofbWPib](https://github.com/DefineX-Studios/parsec-account-switcher/assets/10076396/f75513db-3a3a-4437-97ca-900d3ef1cbe9)

**Comment by electr0de** [comment]
Fixed needs testing @adsau59 run from source, we don't want to keep publishing it messes up the npm.

**Comment by adsau59** [comment]
> 

how do i do that?

**Comment by adsau59** [comment]
fixed
