### ISSUE TITLE
[WIP] return error codes instead of throwing errors

### ISSUE THREAD

**Issue by electr0de** [DefineX-Studios/parsec-account-switcher#28]
# Breakdown:

- [x] Change all the places where you have used try catch to return an error, to return error code.
- [x] Wrap all the function which throws an error in the fs module with a promise using resolve and reject or promisify.

**Comment by electr0de** [comment]
Done

**Comment by adsau59** [comment]
reopening as needed this change

**Comment by adsau59** [comment]
done
