### ISSUE TITLE
if user deletes the shortcut there is no way to create it again

### ISSUE THREAD

**Issue by electr0de** [DefineX-Studios/parsec-account-switcher#47]
STR:
- Launch GUI for the first time
- Notice u have a shortcut
- Delete the shortcut
- There is no way to launch the gui now except for running the `parsec-switcher` command
- even if you do run it, there is no way for a user to recreate the shortcut

Proposed Fix:
create a bat file, and then create 2 shortcuts with it, one on desktop and one in StartMenu

**Comment by adsau59** [comment]
create a bat file, and then create 2 shortcuts with it, one on desktop and one in StartMenu

**Comment by electr0de** [comment]
The launch of program no longer depends on shortcut. If the user deletes the shortcut he may get it back from install dir.
