### ISSUE TITLE
when you get this error, instead tell user to run the app as admin

### ISSUE THREAD

**Issue by adsau59** [DefineX-Studios/parsec-account-switcher#63]
![electron_mvqY0hrNUF](https://github.com/DefineX-Studios/parsec-account-switcher/assets/10076396/7f2eeb13-7f98-43a8-9325-6193507bcdd0)

**Comment by Enigmazflo** [comment]
Added a warning to let people know if they are not running as admin.
[6369f2c](https://github.com/DefineX-Studios/parsec-account-switcher/pull/74/commits/6369f2c9355223202164b1303edeed6335df7201)
